# Generated by Django 5.2.6 on 2025-09-21 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock symbol or asset identifier (e.g., AAPL, MSFT)', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Number of shares/units held', max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price per share/unit at purchase', max_digits=10)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the investment was purchased')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(help_text='The portfolio containing this investment', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.portfolio')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'core_investment',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('split', 'Stock Split'), ('transfer', 'Transfer')], help_text='Type of transaction performed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive for buy, negative for sell)', max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the transaction occurred')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the transaction', null=True)),
                ('investment', models.ForeignKey(help_text='The investment this transaction relates to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.investment')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'core_transaction',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['portfolio', 'symbol'], name='core_invest_portfol_6aaa68_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['symbol'], name='core_invest_symbol_f313d7_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['purchase_date'], name='core_invest_purchas_22aa01_idx'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.UniqueConstraint(fields=('portfolio', 'symbol'), name='unique_portfolio_symbol'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['investment', 'timestamp'], name='core_transa_investm_9d4d37_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='core_transa_transac_6780f1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp'], name='core_transa_timesta_a5c12f_idx'),
        ),
    ]
